name: learn-github-actions-reusable
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
        default: '20'
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '${{ inputs.node-version }}'
      - run: npm install -g bats
      - run: bats -v
