name: Sample 3 Reusable Workflow
run-name: ${{ github.actor }} is learning GitHub Actions with Reusable Workflows
on: [push]
jobs:
  check-bats-version-reusable:
    uses: ./.github/workflows/reusable-bats.yml
    with:
      node-version: '22'
