name: learn-github-actions-with-composite-action
run-name: ${{ github.actor }} is learning GitHub Actions with Composite Action
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/run-bats
        with: 
          node-version: '22'
