name: Sample 2 with Composite Action
run-name: ${{ github.actor }} is learning GitHub Actions with Composite Action
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: ./.github/actions/run-bats
        with: 
          node-version: '22'
